### ISSUE TITLE
locking a row

### ISSUE THREAD

**Issue by kawrou** [kashida2021/qwixx_game#48]
## Description:
The conditions for locking a row are the following:
- A player must have crossed off at least five numbers of the corresponding row.
- If 5 numbers have been crossed off, they have to roll the number (12 / 2) to lock the row.
- Being able to cross out a (12 / 2) is synonymous with locking a row. 
- If a player hasn't crossed out at least 5 numbers, they can't cross out (12 / 2) and lock the row. 
- This can result in a penalty for the active player. 
- Multiple players can lock a row in the same round.

## Task:
- [x] Validate can only mark no.12 for red & yellow row when array length = 5
- [x] Validate can only mark no.2 for green & blue row when array length = 5
- [x] Can only lock red & yellow row if array length = 5 and final number is 12
- [x] Can only lock green & blue row if array length = 5 and final number is 2
- [x] A lock row method for locking a row
- [x] A normalise locked row method to synchronise locked rows after a round ends.
- [x] Locking a row disables the corresponding dice.
- [x] UI should show a row is locked.
## Extension:
The following might need to be done as a separate ticket as it is about player interaction after locking a row rather than the mechanism of locking a row.
- [x] Locking a row means removing (disabling) the corresponding coloured die.
- [x] When a row is locked, it is locked for all players. The UI needs to reflect that.
- [x] All numbers that haven't been marked when a row is locked is disabled.
- [x] Lock button should be disabled when conditions haven't been met.
- [x] Lock button should be enabled when conditions are met.
- [x] The UI for the coloured die should also be handled.
